// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © vkpunique

//@version=5
indicator("Calculator",overlay= true)
import vkpunique/PineHelper/7 as ph

//Replace this with phhelper
method VerticleCell3(table tbl,int rowId, int colId,string cellTitle,string cellText,color backgroundcolor)=>
    table.cell(tbl,colId,rowId,cellTitle,text_color = color.white,bgcolor = color.black)
    table.cell(tbl,colId,rowId+1,cellText,text_color = color.white,bgcolor = backgroundcolor)
    table.cell(tbl,colId,rowId+2,"",text_color = color.white,bgcolor = color(na))

//General variables
[dayOpen,dayHigh,dayLow,dayClose] = request.security(syminfo.tickerid, "1D", [open,high,low,close])
[preDayOpen,preDayHigh,preDayLow,preDayClose] = request.security(syminfo.tickerid, "1D", [open[1],high[1],low[1],close[1]])

//Relative Volume
today_vol = request.security(syminfo.tickerid, "D", volume)
yday_vol = request.security(syminfo.tickerid, "D", volume[1])
avg_vol = request.security(syminfo.tickerid, "D", ta.sma(yday_vol, 20))
rvol_Percentate = (today_vol / avg_vol ) 
GetRvolBGColor(x)=>x>=0.8?color.green:x>=0.5?color(na):x>=0.3?color.orange:color.red

//DCR
dcr_Percentage=(dayClose-dayLow)/(dayHigh-dayLow)
GetDcrBGColor(x)=>x>=0.8?color.green:x>=0.5?color(na):x>=0.3?color.orange:color.red

//Open Calculation
open_Percentage=ph.Percentage(dayOpen,preDayClose)  

//Gap Calculation
gap_Percentage= ph.Percentage(dayLow,preDayClose)  

//Stoploss
slEnum = input.enum(ph.StopLoss.daylow, "Stoploss")
GetSL(x)=>math.round_to_mintick(math.round(x*(1-0.002),2))

float stoploss = switch slEnum
    ph.StopLoss.daylow=>GetSL(dayLow)
    ph.StopLoss.preDayLow=>GetSL(preDayLow)

stoploss_Percentage= (close-stoploss)/stoploss
GetStoplossBGColor(x)=>x>0.04?color.red: x>=0.025?color.orange:x>=0.01?color(na):color.green

//Quantity
int positionSize=input.int(300, "Position", minval=200, maxval=1000, step=1)*1000
int qty=math.round(positionSize/close)

int rowId=0
int colId=0
if barstate.islast 
    var dashboard= table.new("top_right",2,20)

    VerticleCell3( dashboard,rowId,colId,"RVol",ph.ToPercentage(rvol_Percentate),GetRvolBGColor(rvol_Percentate))
    colId:=colId+1

    VerticleCell3( dashboard,rowId,colId,"DCR",ph.ToPercentage(dcr_Percentage), GetDcrBGColor(dcr_Percentage))
    colId:=colId+1

    rowId:=rowId+3
    colId:=0
    VerticleCell3(dashboard,rowId,colId,"Open",ph.ToPercentage(open_Percentage),ph.GetBGColorUp(open_Percentage,-0.01,0,0.01))
    colId:=colId+1

    VerticleCell3(dashboard,rowId,colId,"Gap",ph.ToPercentage(gap_Percentage),ph.GetBGColorUp(gap_Percentage,-0.01,0,0.01))
    colId:=colId+1

    rowId:=rowId+3
    colId:=0
    VerticleCell3(dashboard,rowId,colId,"SL%",ph.ToPercentage(stoploss_Percentage),GetStoplossBGColor(stoploss_Percentage))
    colId:=colId+1

    VerticleCell3(dashboard,rowId,colId,"SL AT",str.tostring(slEnum),color(na))
    colId:=colId+1

    rowId:=rowId+3
    colId:=0
    VerticleCell3(dashboard,rowId,colId,"SL",ph.ToOneDecimal(stoploss),color(na))
    colId:=colId+1

    VerticleCell3(dashboard,rowId,colId,"QTY",ph.ToNoDecimal(qty),color(na))
    colId:=colId+1