 //@version=5
indicator("Test",overlay= true)

//Comman Variables
var rowId=0
var colId=0
var textColor=color.white

//Function to Get color value
GetEmaBGColor(x)=>x>=0?color.green:color.red

method Cells(table tbl,int rowId, int colId,string cellText,color backgroundcolor)=>
    table.cell(tbl,colId,rowId,cellText,text_color = textColor,bgcolor = backgroundcolor)


//EMA Calculation
ema10 = ta.ema(close, 10)
ema21 = ta.ema(close, 21)
ema50 = ta.ema(close, 50)

ema10_Percentate=(close-ema10)/ema10
ema21_Percentate=(close-ema21)/ema21
ema50_Percentate=(close-ema50)/ema50

if barstate.islast
    var dashboard= table.new("top_center",10,2)

    dashboard.Cells(0,colId,"EMA 10",color.black)
    dashboard.Cells(1,colId, str.tostring(ema10_Percentate,"0.00%"), GetEmaBGColor(ema10_Percentate))
    colId:=colId+1

    dashboard.Cells(0,colId,"EMA 21",color.black)
    dashboard.Cells(1,colId, str.tostring(ema21_Percentate,"0.00%"), GetEmaBGColor(ema21_Percentate))
    colId:=colId+1

    dashboard.Cells(0,colId,"EMA 50",color.black)
    dashboard.Cells(1,colId, str.tostring(ema50_Percentate,"0.00%"), GetEmaBGColor(ema50_Percentate))
    colId:=colId+1
 
    dashboard.Cells(0,colId,"ATH",color.black)
    dashboard.Cells(1,colId, "0", GetEmaBGColor(0))
    colId:=colId+1

    dashboard.Cells(0,colId,"RVol",color.black)
    dashboard.Cells(1,colId, "0", GetEmaBGColor(0))
    colId:=colId+1
