//@version=5
indicator("Test",overlay= true)
int rowId=0
int colId=0
var textColor=color.white

//Chart info
dayLow=request.security(syminfo.tickerid,"1D",low)
dayOpen=request.security(syminfo.tickerid,"1D",open)
preDayClose= request.security(syminfo.tickerid,"1D",close[1])
preDayLow= request.security(syminfo.tickerid,"1D",low[1])

//Trigger Calculation
var triggerMap= map.new<string,float>()
triggerMap.put("MOIL",545)
triggerMap.put("GMDCLTD",404)
triggerMap.put("TRIVENI",398)
triggerMap.put("MANGLMCEM",928)
triggerMap.put("CHAMBLFERT",524)
triggerMap.put("JINDALSTEL",1064)
triggerMap.put("IONEXCHANG",665)
triggerMap.put("QUICKHEAL",543)
triggerMap.put("TRACXN",99)
triggerMap.put("OLECTRA",1866)
triggerMap.put("JBMA",2200)
triggerMap.put("KIOCL",483)
triggerMap.put("ACE",1550)
triggerMap.put("ICEMAKE",920)
triggerMap.put("NEWGEN",1028)

float trigger=triggerMap.contains(syminfo.ticker)?triggerMap.get(syminfo.ticker):0
trigger_Percentage=trigger>0? (close-trigger)/trigger:0
GetTriggerBGColor(x)=>x>=0?color.green:x>=-0.02?color.orange:color.red

//Open Calculation
open_Percentage=(dayOpen-preDayClose)/dayOpen
GetOpenBGColor(x)=>x>=0.01?color.green:x>=-0.005?color.orange:color.red

//Gap Calculation
gap_Percentage= (dayLow-preDayClose)/dayLow
GetGapBGColor(x)=>x>=0?color.green:x>=-0.01?color.orange:color.red

//Qty Calculation
int positionSize=input.int(300, "Position", minval=200, maxval=1000, step=1)*1000
int qty=math.round(positionSize/close)

//Stoploss
enum sl
    daylow ="Day Low"
    preDayLow  = "Pre Day Low"

slEnum = input.enum(sl.daylow, "Stoploss")
GetSL(x)=>math.round(x*(1-0.002),2)

float stoploss = switch slEnum
    sl.daylow=>GetSL(dayLow)
    sl.preDayLow=>GetSL(preDayLow)

stoploss_Percentage= (close-stoploss)/stoploss
GetStoplossBGColor(x)=>x<=0.02?color.green:x<=0.04?color.orange:color.red

//Holding Stock Calculation
type Trade
    float BuyPrice
    float Stoploss

var holdingMap= map.new<string,Trade>()
holdingMap.put("IREDA",Trade.new(181.6,219))
holdingMap.put("HBLPOWER",Trade.new(518.6,531))
holdingMap.put("OLECTRA",Trade.new(1903.35,1815.85))

float buyPrice=holdingMap.contains(syminfo.ticker)?holdingMap.get(syminfo.ticker).BuyPrice:0
float gain_Percentage=buyPrice>0? (close-buyPrice) /buyPrice:0
GetGainBGColor(x)=>x>=0?color.green:color.red

float sellPrice=holdingMap.contains(syminfo.ticker)?holdingMap.get(syminfo.ticker).Stoploss:0
float sellPrice_Percentage=sellPrice>0? sellPrice/buyPrice-1:0

method Cells(table tbl,int rowId, int colId,string cellText,color backgroundcolor)=>
    table.cell(tbl,colId,rowId,cellText,text_color = textColor,bgcolor = backgroundcolor)

var dashboard= table.new("top_right",2,15)
dashboard.Cells(rowId,colId,"Helper",color.blue)
//Merge First Row
table.merge_cells(dashboard,colId,rowId,colId+1,rowId)
rowId:=rowId+2

dashboard.Cells(rowId,colId,"Trigger",color.black)
dashboard.Cells(rowId,colId+1,trigger>0?str.tostring(trigger_Percentage,"0.00%"):"-",GetTriggerBGColor(trigger_Percentage))
rowId:=rowId+1

dashboard.Cells(rowId,colId,"Open",color.black)
dashboard.Cells(rowId,colId+1, str.tostring(open_Percentage,"0.00%"),GetOpenBGColor(open_Percentage))
rowId:=rowId+1

dashboard.Cells(rowId,colId,"Gap",color.black)
dashboard.Cells(rowId,colId+1, str.tostring(gap_Percentage,"0.00%"),GetGapBGColor(gap_Percentage))
rowId:=rowId+1

dashboard.Cells(rowId,colId,"SL%",color.black)
dashboard.Cells(rowId,colId+1,str.tostring(stoploss_Percentage,"0.00%"),GetStoplossBGColor(stoploss_Percentage))
rowId:=rowId+1

dashboard.Cells(rowId,colId,"SL",color.black)
dashboard.Cells(rowId,colId+1,str.tostring(stoploss),GetStoplossBGColor(stoploss_Percentage))
rowId:=rowId+1

dashboard.Cells(rowId,colId,"QTY",color.black)
dashboard.Cells(rowId,colId+1, str.tostring(qty),color.green)
rowId:=rowId+1

//For stocks i am holding
dashboard.Cells(rowId,colId,"Holding",color.blue)
table.merge_cells(dashboard,colId,rowId,colId+1,rowId)
rowId:=rowId+1

dashboard.Cells(rowId,colId,"Gain",color.black)
dashboard.Cells(rowId,colId+1,buyPrice>0? str.tostring(gain_Percentage,"0.00%"):"-",GetGainBGColor(stoploss_Percentage))
rowId:=rowId+1

dashboard.Cells(rowId,colId,"Risk",color.black)
dashboard.Cells(rowId,colId+1,sellPrice>0?str.tostring(sellPrice_Percentage,"0.00%"):"-",GetGainBGColor(sellPrice_Percentage))
rowId:=rowId+1
