//@version=5 
indicator(title="Test", overlay=true)
 

var rowId=0
var colId=0
var textColor=color.white
method Cells(table tbl,int rowId, int colId,string cellText,color backgroundcolor)=>
    table.cell(tbl,colId,rowId,cellText,text_color = textColor,bgcolor = backgroundcolor)

var dashboard= table.new("top_right",3,10)
dashboard.Cells(rowId,colId,"Stock Info",color.blue)
table.merge_cells(dashboard,0,0,1,0)
dashboard.Cells(rowId+1,colId,"Sector",color.black)
dashboard.Cells(rowId+1,colId+1,syminfo.sector,color.maroon)

dashboard.Cells(rowId+2,colId,"Industry",color.black)
dashboard.Cells(rowId+2,colId+1,syminfo.industry,color.maroon)
 