indicator("Test",overlay= true)

newbar(res) => ta.change(time(res)) == 0 ? 0 : 1
// Returns 1st min close at open RTH at 09:30 close of the current symbol.
USAOPENtimeOk8h = ( timeframe.period == "480" and timestamp(syminfo.timezone, year(time), month(time), dayofmonth(time), 2, 0) == time)
USAOPENtimeOk7h = ( timeframe.period == "420" and timestamp(syminfo.timezone, year(time), month(time), dayofmonth(time), 8, 0) == time)
USAOPENtimeOk6h = ( timeframe.period == "360" and timestamp(syminfo.timezone, year(time), month(time), dayofmonth(time), 6, 0) == time)
USAOPENtimeOk5h = ( timeframe.period == "300" and timestamp(syminfo.timezone, year(time), month(time), dayofmonth(time), 9, 0) == time)
USAOPENtimeOk4h = ( timeframe.period == "240" and timestamp(syminfo.timezone, year(time), month(time), dayofmonth(time), 6, 0) == time)
USAOPENtimeOk3h = ( timeframe.period == "180" and timestamp(syminfo.timezone, year(time), month(time), dayofmonth(time), 9, 0) == time)
USAOPENtimeOk2h = ( timeframe.period == "120" and timestamp(syminfo.timezone, year(time), month(time), dayofmonth(time), 8, 0) == time)
USAOPENtimeOk1h = ( timeframe.period == "60" and timestamp(syminfo.timezone, year(time), month(time), dayofmonth(time), 9, 0) == time)
USAOPENtimeOk = ( timestamp(syminfo.timezone, year(time), month(time), dayofmonth(time), 9, 15) == time)
Timeok = USAOPENtimeOk or USAOPENtimeOk1h or USAOPENtimeOk2h or USAOPENtimeOk3h or USAOPENtimeOk4h or USAOPENtimeOk5h or USAOPENtimeOk6h or USAOPENtimeOk7h or USAOPENtimeOk8h or timeframe.period == "D"

firststminHigh = request.security_lower_tf(syminfo.tickerid, "1", high)

Highvalue_d07 = timeframe.period == "D" and array.size(firststminHigh)>990? array.get(firststminHigh,990):na
Highvalue_d18 = timeframe.period == "D" and array.size(firststminHigh)>930? array.get(firststminHigh,930):na
Highvalue_480 = timeframe.period == "480" and array.size(firststminHigh)>450? array.get(firststminHigh,450):na
Highvalue_420 = timeframe.period == "420" and array.size(firststminHigh)>90? array.get(firststminHigh,90):na
Highvalue_360 = timeframe.period == "360" and array.size(firststminHigh)>210? array.get(firststminHigh,210):na
Highvalue_300 = timeframe.period == "300" and array.size(firststminHigh)>30? array.get(firststminHigh,30):na
Highvalue_240 = timeframe.period == "240" and array.size(firststminHigh)>210? array.get(firststminHigh,210):na
Highvalue_180 = timeframe.period == "180" and array.size(firststminHigh)>30? array.get(firststminHigh,30):na
Highvalue_120 = timeframe.period == "120" and array.size(firststminHigh)>90? array.get(firststminHigh,90):na
Highvalue_60 = timeframe.period == "60" and array.size(firststminHigh)>30? array.get(firststminHigh,30):na
Highvalue_0 = newbar (timeframe.period) and array.size(firststminHigh) > 0 ? array.first(firststminHigh): na

Highvalue = timeframe.isintraday==false and (syminfo.type == "futures" or syminfo.type == "index" or syminfo.type == "forex" ) ?Highvalue_d18: timeframe.isintraday==false and (syminfo.type == "forex" or syminfo.type == "crypto" ) ?Highvalue_d07: USAOPENtimeOk8h ?Highvalue_480:USAOPENtimeOk7h?Highvalue_420:USAOPENtimeOk6h?Highvalue_360:USAOPENtimeOk5h?Highvalue_300:USAOPENtimeOk4h?Highvalue_240:USAOPENtimeOk3h?Highvalue_180:USAOPENtimeOk2h?Highvalue_120:USAOPENtimeOk1h?Highvalue_60:USAOPENtimeOk? Highvalue_0 :na
var float fmh = na
fmh := Timeok ?Highvalue: fmh[1]

firststminLow = request.security_lower_tf(syminfo.tickerid, "1", low)

Lowvalue_d07 = timeframe.period == "D" and array.size(firststminLow)>990? array.get(firststminLow,990):na
Lowvalue_d18 = timeframe.period == "D" and array.size(firststminLow)>930? array.get(firststminLow,930):na
Lowvalue_480 = timeframe.period == "480" and array.size(firststminLow)>450? array.get(firststminLow,450):na
Lowvalue_420 = timeframe.period == "420" and array.size(firststminLow)>90? array.get(firststminLow,90):na
Lowvalue_360 = timeframe.period == "360" and array.size(firststminLow)>210? array.get(firststminLow,210):na
Lowvalue_300 = timeframe.period == "300" and array.size(firststminLow)>30? array.get(firststminLow,30):na
Lowvalue_240 = timeframe.period == "240" and array.size(firststminLow)>210? array.get(firststminLow,210):na
Lowvalue_180 = timeframe.period == "180" and array.size(firststminLow)>30? array.get(firststminLow,30):na
Lowvalue_120 = timeframe.period == "120" and array.size(firststminLow)>90? array.get(firststminLow,90):na
Lowvalue_60 = timeframe.period == "60" and array.size(firststminLow)>30? array.get(firststminLow,30):na
Lowvalue_0 = newbar (timeframe.period) and array.size(firststminLow) > 0 ? array.first(firststminLow): na

Lowvalue = timeframe.isintraday==false and (syminfo.type == "futures" or syminfo.type == "index" or syminfo.type == "forex" ) ?Lowvalue_d18: timeframe.isintraday==false and (syminfo.type == "forex" or syminfo.type == "crypto" ) ?Lowvalue_d07: USAOPENtimeOk8h ?Lowvalue_480:USAOPENtimeOk7h?Lowvalue_420:USAOPENtimeOk6h?Lowvalue_360:USAOPENtimeOk5h?Lowvalue_300:USAOPENtimeOk4h?Lowvalue_240:USAOPENtimeOk3h?Lowvalue_180:USAOPENtimeOk2h?Lowvalue_120:USAOPENtimeOk1h?Lowvalue_60:USAOPENtimeOk? Lowvalue_0 :na
var float fml = na

fml := Timeok ?Lowvalue: fml[1]

var table myTable = table.new(position = position.top_right, columns = 2, rows = 7, bgcolor = color.yellow, border_width = 1)

// Populate the table
table.cell(myTable, 0, 0, "First High")
table.cell(myTable, 1, 0, str.tostring(fmh))

table.cell(myTable, 0, 1, "First Low")
table.cell(myTable, 1, 1, str.tostring(fml))